/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DogexorRexUwU (https://sketchfab.com/oscar.lopez.riviello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xbox-inalambric-controller-white-f18a70fc10414ef5a39b55de68f12823
Title: Xbox Inalambric Controller (White)
*/

"use client";
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function XboxController(props) {
  const { nodes, materials } = useGLTF('/models/xbox_inalambric_controller_white(1).glb');
  const meshRef = useRef();
  useFrame(() => {
    if (meshRef.current) meshRef.current.rotation.y += 0.005;
  });
  return (
    <group {...props} dispose={null} ref={meshRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.material}
        material-color="#877569"
        position={[0, -0.25, 0.293]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload('/models/xbox_inalambric_controller_white(1).glb');
